/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    scala
    `java-library`
    bloop
    alias(libs.plugins.shadow)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Scala 2.12 in our library project
    implementation(libs.scala.library)

    implementation(libs.guava)
    implementation(libs.scopt)

    // Spark dependencies should be provided by the cluster at runtime
    compileOnly(libs.spark.core)
    compileOnly(libs.spark.sql)
    compileOnly(libs.spark.streaming)
    compileOnly(libs.spark.hive)

    // Spark dependencies are needed for tests
    testImplementation(libs.spark.core)
    testImplementation(libs.spark.sql)
    testImplementation(libs.spark.streaming)
    testImplementation(libs.spark.hive)

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest.v2.v12)
    testImplementation(libs.junit.v4.v13.v2.v12)

    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scala.xml.v2.v12)

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
}

tasks.shadowJar {
    archiveClassifier.set("")
    mergeServiceFiles()
}

tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.additionalParameters.add("-target:jvm-1.8")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
